#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int rotate = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F020000
			public const int words = 2130837504;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int black = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int blue = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int red = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int white = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int arm1 = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int arm2 = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int body = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int gallows = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int head = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int leg1 = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int leg2 = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int letter_bg = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int letter_down = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int letter_up = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int title = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int trophy = 2131034123;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int action_menu = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int alphabets = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int btnhome = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int btnret = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int edtname = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int gv = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int image = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int manarm1 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int manarm2 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int manbody = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int manhead = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int manleg1 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int manleg2 = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int rl = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int txt = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int txtname = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int txtscore = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int words = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int choice = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int game = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int letter = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int result = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int splashscreen = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int totalscores = 2131165189;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int menu1 = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int Icon = 2131296256;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int arm = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int body = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int gallows = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int head = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int leg = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int menuItem1 = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int play = 2131361800;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
